"""Marketplace generation locks (F2-7b).

The committed plugins/ tree, .claude-plugin/marketplace.json and
knowledge/skills-manifest.json are GENERATED by
scripts/marketplace_gen.py from config/skills-curated.yaml + the
departments/ tree. These tests drift-gate the committed artifacts
against a fresh run and pin the invariants that make the distribution
cut safe: legacy entry preserved verbatim, curated and plugin sets
disjoint per dept,
collision slugs banned from curated, export hygiene, version==VERSION.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPTS_DIR = REPO_ROOT / "scripts"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

import marketplace_gen as mg  # noqa: E402

VERSION = (REPO_ROOT / "VERSION").read_text(encoding="utf-8").strip()


@pytest.fixture(scope="module")
def marketplace() -> dict:
    return json.loads(
        (REPO_ROOT / ".claude-plugin" / "marketplace.json")
        .read_text(encoding="utf-8")
    )


@pytest.fixture(scope="module")
def skills_manifest() -> dict:
    return json.loads(
        (REPO_ROOT / "knowledge" / "skills-manifest.json")
        .read_text(encoding="utf-8")
    )


@pytest.fixture(scope="module")
def curated() -> dict[str, list[str]]:
    return mg.load_curated()


@pytest.fixture(scope="module")
def subskills() -> dict[str, list[str]]:
    return mg.dept_subskills()


def test_committed_tree_is_byte_identical_to_generator(tmp_path, monkeypatch):
    """Full drift gate: regenerate into a sandbox, compare byte-for-byte
    with the committed plugins/ + marketplace.json + skills-manifest."""
    sandbox = tmp_path / "repo"
    sandbox.mkdir()
    (sandbox / ".claude-plugin").mkdir()
    (sandbox / "knowledge").mkdir()
    # Seed the sandbox manifest with the COMMITTED one — the generator
    # extends it, so starting from the committed file must be a no-op.
    (sandbox / ".claude-plugin" / "marketplace.json").write_text(
        (REPO_ROOT / ".claude-plugin" / "marketplace.json")
        .read_text(encoding="utf-8"), encoding="utf-8")
    monkeypatch.setattr(mg, "PLUGINS_DIR", sandbox / "plugins")
    monkeypatch.setattr(
        mg, "MARKETPLACE_JSON", sandbox / ".claude-plugin" / "marketplace.json")
    monkeypatch.setattr(
        mg, "SKILLS_MANIFEST_JSON",
        sandbox / "knowledge" / "skills-manifest.json")
    mg.generate()

    for rel in (".claude-plugin/marketplace.json",
                "knowledge/skills-manifest.json"):
        assert (sandbox / rel).read_text(encoding="utf-8") == \
            (REPO_ROOT / rel).read_text(encoding="utf-8"), (
                f"{rel} drifted — run `python scripts/marketplace_gen.py` "
                f"and commit"
            )

    committed = sorted(
        p.relative_to(REPO_ROOT / "plugins")
        for p in (REPO_ROOT / "plugins").rglob("*") if p.is_file()
    )
    fresh = sorted(
        p.relative_to(sandbox / "plugins")
        for p in (sandbox / "plugins").rglob("*") if p.is_file()
    )
    assert committed == fresh, "plugins/ file set drifted — regenerate"
    for rel in committed:
        assert (REPO_ROOT / "plugins" / rel).read_bytes() == \
            (sandbox / "plugins" / rel).read_bytes(), (
                f"plugins/{rel} drifted — regenerate"
            )


def test_marketplace_identity_and_version(marketplace):
    assert marketplace["name"] == "arkaos"
    assert marketplace["owner"]["name"] == "WizardingCode"
    assert marketplace["version"] == VERSION, (
        "top-level version must track the VERSION file — regenerate on bump"
    )
    assert marketplace["metadata"]["version"] == VERSION


def test_legacy_dev_bundle_entry_preserved(marketplace):
    legacy = [p for p in marketplace["plugins"]
              if p["name"] == "arkaos-dev-skills"]
    assert len(legacy) == 1
    assert len(legacy[0]["skills"]) == 10
    assert marketplace["plugins"][0]["name"] == "arkaos-dev-skills", (
        "legacy entry must stay first — installed machines resolve it"
    )


def test_every_dept_entry_points_at_a_valid_plugin(marketplace):
    dept_entries = [p for p in marketplace["plugins"]
                    if p["name"] != "arkaos-dev-skills"]
    assert len(dept_entries) == 16  # every dept with sub-skills; quality has none
    for entry in dept_entries:
        assert re.fullmatch(r"arkaos-[a-z]+", entry["name"])
        assert entry["source"] == f"./plugins/{entry['name']}"
        plugin_dir = REPO_ROOT / "plugins" / entry["name"]
        manifest = json.loads(
            (plugin_dir / ".claude-plugin" / "plugin.json")
            .read_text(encoding="utf-8"))
        assert manifest["name"] == entry["name"]
        assert manifest["version"] == VERSION
        assert (plugin_dir / "skills").is_dir()


def test_complement_partition_per_dept(curated, subskills):
    """Curated and plugin sets are disjoint and together cover the dept."""
    for dept, slugs in subskills.items():
        cur = set(curated.get(dept, []))
        plugin_dir = REPO_ROOT / "plugins" / f"arkaos-{dept}"
        shipped = (
            {p.name for p in (plugin_dir / "skills").iterdir()}
            if plugin_dir.is_dir() else set()
        )
        assert cur & shipped == set(), f"{dept}: curated leaked into plugin"
        assert cur | shipped == set(slugs), f"{dept}: partition incomplete"


def test_curated_slugs_exist_and_avoid_collisions(curated, subskills):
    collisions = set(mg.collision_slugs(subskills))
    for dept, slugs in curated.items():
        for slug in slugs:
            assert (REPO_ROOT / "departments" / dept / "skills" / slug /
                    "SKILL.md").is_file(), f"curated {dept}/{slug} missing"
            assert slug not in collisions, (
                f"curated slug {slug!r} is a later-wins collision — those "
                f"live ONLY in plugins where the namespace disambiguates"
            )


def test_curated_default_stays_in_the_60_80_band(curated, skills_manifest):
    structural = skills_manifest["structural"]
    total = (1 + len(structural["hubs"]) + len(structural["meta"])
             + sum(len(s) for s in curated.values()))
    assert 60 <= total <= 80, (
        f"default install would carry {total} skills — the curated cut "
        f"exists to hold the 60-80 band"
    )


def test_generated_skills_hygiene():
    """No internal frontmatter/links survive the export conversion."""
    for md in (REPO_ROOT / "plugins").glob("*/skills/*/SKILL.md"):
        body = md.read_text(encoding="utf-8")
        assert "allowed-tools" not in body, md
        assert "kb-first-prefix" not in body, md
        assert "](/arka" not in body, md
        name = re.search(r"^name:\s*(.+)$", body, re.M)
        assert name and name.group(1).strip() == md.parent.name, (
            f"{md}: frontmatter name must equal the dir slug"
        )


def test_skills_manifest_classifies_every_subskill(skills_manifest, subskills):
    manifest_skills = skills_manifest["skills"]
    all_slugs = {s for slugs in subskills.values() for s in slugs}
    assert set(manifest_skills) == all_slugs
    for slug, entry in manifest_skills.items():
        assert entry["curated"] or entry["plugins"], (
            f"{slug}: neither curated nor reachable via a plugin"
        )
        for ref in entry["plugins"]:
            assert re.fullmatch(r"arkaos-[a-z]+@arkaos", ref)


def test_arka_link_unwrap_fixes_the_known_export_leak():
    converted = mg.convert_skill(
        "---\nname: x\n---\nSee [Browser Integration Pattern](/arka).\n", "x")
    assert "](/arka" not in converted
    assert "Browser Integration Pattern" in converted
