"""Post-task skill proposer (PR44 v2.63.0).

Constitution rule (NON-NEGOTIABLE): after every completed substantive
task, the system MUST evaluate whether the work just done represents a
repeatable capability that should be promoted to a permanent skill.

Mirror of the PR20 reorganizer pattern but focused on capability-capture.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

_COMPLETION_PATTERNS: tuple[re.Pattern[str], ...] = (
    re.compile(r"\[arka:gate:4\]", re.IGNORECASE),
    re.compile(r"\[arka:phase:13\]", re.IGNORECASE),  # legacy, v4.1 window
    re.compile(r"\barc complete\b", re.IGNORECASE),
)

_BYPASS_PATTERNS: tuple[re.Pattern[str], ...] = (
    re.compile(r"\[arka:trivial\]", re.IGNORECASE),
    re.compile(r"\[arka:skill-skip\]", re.IGNORECASE),
)

_SKILL_WORTHY_HINTS: tuple[re.Pattern[str], ...] = (
    re.compile(r"\b\d+-phase\b", re.IGNORECASE),
    re.compile(r"\bworkflow\b", re.IGNORECASE),
    re.compile(r"\bskill\b", re.IGNORECASE),
    re.compile(r"\btemplate\b", re.IGNORECASE),
    re.compile(r"\bprocedure\b", re.IGNORECASE),
    re.compile(r"\bplaybook\b", re.IGNORECASE),
    re.compile(r"\bchecklist\b", re.IGNORECASE),
)

_TRIVIAL_WORD_THRESHOLD: int = 15
_DEFAULT_OUTPUT_DIR: Path = Path.home() / ".arkaos" / "skill-proposals"


@dataclass(frozen=True)
class SkillProposal:
    """Outcome of a skill-evaluation pass."""
    should_propose: bool
    reason: str
    suggested_slug: str | None
    proposal_path: Path | None
    proposal_markdown: str | None


def evaluate(
    transcript_tail: str,
    *,
    output_dir: Path | None = None,
    today: str | None = None,
) -> SkillProposal:
    """Classify the closing transcript tail; propose a skill if warranted."""
    text = transcript_tail or ""

    if _has_bypass(text):
        return SkillProposal(False, "bypass-marker", None, None, None)

    if not _has_completion_signal(text):
        return SkillProposal(False, "no-completion-signal", None, None, None)

    if _is_trivial_length(text):
        return SkillProposal(False, "trivial-length", None, None, None)

    hint_count = sum(1 for pat in _SKILL_WORTHY_HINTS if pat.search(text))
    if hint_count < 2:
        return SkillProposal(False, "below-skill-hint-floor", None, None, None)

    slug = _suggest_slug(text)
    markdown = _render_proposal(text, slug, today=today)
    out_dir = output_dir or _DEFAULT_OUTPUT_DIR
    out_dir.mkdir(parents=True, exist_ok=True)
    iso_today = today or datetime.now(timezone.utc).strftime("%Y-%m-%d")
    path = out_dir / f"{iso_today}-{slug}.md"
    path.write_text(markdown, encoding="utf-8")
    return SkillProposal(True, "proposed", slug, path, markdown)


def _has_completion_signal(text: str) -> bool:
    return any(p.search(text) for p in _COMPLETION_PATTERNS)


def _has_bypass(text: str) -> bool:
    return any(p.search(text) for p in _BYPASS_PATTERNS)


def _is_trivial_length(text: str) -> bool:
    return len(text.split()) < _TRIVIAL_WORD_THRESHOLD


def _suggest_slug(text: str) -> str:
    for pat in _SKILL_WORTHY_HINTS:
        m = pat.search(text)
        if m:
            anchor = m.group(0).lower()
            return _slugify(f"capability-{anchor}")
    return "capability-task"


def _slugify(value: str) -> str:
    out = re.sub(r"[^a-z0-9-]+", "-", value.lower()).strip("-")
    return out[:60] if out else "capability"


def _render_proposal(text: str, slug: str, *, today: str | None) -> str:
    iso = today or datetime.now(timezone.utc).strftime("%Y-%m-%d")
    excerpt = text.strip()
    if len(excerpt) > 1000:
        excerpt = excerpt[:1000].rstrip() + "..."
    return (
        f"# Skill Proposal — {slug}\n\n"
        f"> Auto-generated by skill_proposer.evaluate on {iso}. "
        "Review before promoting.\n\n"
        "## Why this proposal exists\n\n"
        "The constitution rule mandatory-skill-evaluation (NON-NEGOTIABLE) "
        "fires after every completed substantive task. This proposal "
        "represents a candidate capability the system thinks could be "
        "captured as a permanent skill in a department.\n\n"
        "## Transcript excerpt (last 1000 chars)\n\n"
        f"```\n{excerpt}\n```\n\n"
        "## Suggested next steps\n\n"
        "1. Decide if this capability deserves its own skill.\n"
        "2. Pick the target department (/dev, /brand, /saas, ...).\n"
        "3. Manually scaffold departments/<dept>/skills/<slug>/SKILL.md.\n"
        "4. Delete this proposal file once acted on.\n\n"
        "## Status\n\n"
        "- Reviewed by operator: NO\n"
        "- Promoted to skill: NO\n"
    )
