"""Generate THE-ARKAOS-GUIDE.md — the one-file, send-it-to-someone guide.

Docs-as-code: every number comes from the ``docs_stats`` counters, every
department row from ``knowledge/commands-registry.json``; the prose
skeleton lives here, in one place. ``tests/python/test_guide_gen.py``
fails the suite on byte drift generator<->committed AND on the guide
growing past its size budget — a shareable guide that nobody reads is
the documented anti-pattern this generator exists to avoid.

Run: ``~/.arkaos/bin/arka-py scripts/guide_gen.py``
"""

from __future__ import annotations

import json
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent / "tools"))

from docs_stats import (
    count_adrs,
    count_agents,
    count_departments,
    count_skills,
    read_version,
    repo_root,
)

GUIDE_NAME = "THE-ARKAOS-GUIDE.md"
SIZE_BUDGET_BYTES = 15_000


def _department_rows(root: Path) -> list[tuple[str, int]]:
    """(prefix, command count) rows, keyed by the REAL command token.

    Keying by the registry's department label printed a dead
    ``/leadership`` (the commands are ``/lead ...``) — the token is what
    a reader can actually type, and stays correct if a label and its
    prefix ever diverge again.
    """
    registry = root / "knowledge" / "commands-registry.json"
    data = json.loads(registry.read_text(encoding="utf-8"))
    counts = Counter(
        str(cmd.get("command") or "").split()[0].lstrip("/")
        for cmd in data.get("commands", [])
        if str(cmd.get("command") or "").startswith("/")
    )
    return sorted(counts.items())


def render(root: Path) -> str:
    version = read_version(root)
    agents = count_agents(root)
    departments = count_departments(root)
    skills = count_skills(root)
    adrs = count_adrs(root)
    dept_rows = _department_rows(root)
    total_commands = sum(count for _, count in dept_rows)

    lines = [
        "# The ArkaOS Guide",
        "",
        f"> v{version} — {agents['files']} agents, {departments} "
        f"departments, {skills['core']} skills, {total_commands} "
        f"commands, {adrs} ADRs.",
        "> One file, everything you need to start. Generated by "
        "`scripts/guide_gen.py` — never hand-edited.",
        "",
        "## What it is",
        "",
        "ArkaOS is an operating system for AI agent teams: specialized",
        "departments with framework-backed agents, a constitution with a",
        "Quality Gate that holds veto power, and an evidence flow where",
        "gates pass on tool output read from disk — never on narration.",
        "",
        "## Start here",
        "",
        "```bash",
        "npx arkaos install     # detects your runtime, installs the core",
        "npx arkaos doctor      # canonical health check (venv, hooks,",
        "                       # fastpath, security advisory)",
        "```",
        "",
        "Then inside your runtime: `/arka setup` (profile) and `/do <what",
        "you need>` — plain language routes to the right department.",
        "",
        "## Keep it updated (two steps)",
        "",
        "```bash",
        "npx arkaos@latest update   # step 1: core, hooks, CLI",
        "```",
        "",
        "Then `/arka update` inside the runtime — step 2 syncs every",
        "project (skills, MCP configs, settings, stack rules).",
        "",
        "## Departments",
        "",
        "Every request routes through a department squad — ArkaOS never",
        "answers as a generic assistant.",
        "",
        "| Prefix | Commands |",
        "|---|---|",
        *[f"| `/{dept}` | {count} |" for dept, count in dept_rows],
        "",
        "## How work ships",
        "",
        "1. **G1 CONTEXT** — routing + grounding before anything runs.",
        "2. **G2 PLAN** — explicit approval before code.",
        "3. **G3 EXECUTE** — real test runs with exit codes on record.",
        "4. **G4 REVIEW** — the Quality Gate (CQO + copy + tech reviewers)",
        "   issues a binary APPROVED/REJECTED; failing evidence can never",
        "   be overridden by narrative.",
        "",
        "## Go deeper",
        "",
        "- Wiki: https://github.com/andreagroferreira/arka-os/wiki",
        "- npm: https://www.npmjs.com/package/arkaos",
        "- Dashboard: `npx arkaos dashboard` (localhost:3333)",
        "",
    ]
    return "\n".join(lines)


def main(root: Path | None = None) -> int:
    root = root or repo_root()
    guide = render(root)
    size = len(guide.encode("utf-8"))
    if size > SIZE_BUDGET_BYTES:
        print(f"guide over budget: {size} > {SIZE_BUDGET_BYTES} bytes")
        return 1
    (root / GUIDE_NAME).write_text(guide, encoding="utf-8")
    print(f"guide generated: {GUIDE_NAME} ({size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
