"""Workflows catalog generator — every workflow YAML in the system.

Documents the complete workflow surface: the enterprise, focused, and
specialist workflows defined under ``departments/*/workflows/*.yaml``.
Single source of truth: the workflow YAML files themselves — never
hand-typed counts. This script GENERATES:

- ``docs/WORKFLOWS-CATALOG.md`` — per-department workflow reference
  with tier, command, phase count, gate types, and quality-gate flag.

Regenerate + commit after touching any workflow YAML, department
layout, or VERSION:

    python scripts/workflows_catalog_gen.py

``tests/python/test_workflows_catalog_gen.py`` drift-gates the
committed file against a fresh in-memory run, byte for byte.
"""

from __future__ import annotations

import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover - venv-only dependency
    yaml = None

REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT = REPO_ROOT / "docs" / "WORKFLOWS-CATALOG.md"

DEPT_TITLES = {
    "dev": "Development",
    "marketing": "Marketing",
    "brand": "Brand & Design",
    "finance": "Finance",
    "strategy": "Strategy",
    "ecom": "E-Commerce",
    "kb": "Knowledge",
    "ops": "Operations",
    "pm": "Project Management",
    "saas": "SaaS",
    "landing": "Landing Pages",
    "content": "Content",
    "community": "Communities",
    "sales": "Sales",
    "leadership": "Leadership",
    "org": "Organization",
}

TIER_LABELS = {
    "enterprise": "Enterprise (7-10 phases, mandatory Quality Gate)",
    "focused": "Focused (3-4 phases)",
    "specialist": "Specialist (1-2 phases)",
}


def _workflow_entry(path: Path) -> dict | None:
    """id, name, description, tier, command, phases, gates from YAML."""
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except Exception:
        return None
    if not isinstance(data, dict) or "id" not in data:
        return None
    phases = data.get("phases", []) or []
    gate_types = []
    for phase in phases:
        gate = phase.get("gate") if isinstance(phase, dict) else None
        if isinstance(gate, dict) and gate.get("type"):
            gate_types.append(str(gate["type"]))
    return {
        "id": str(data["id"]),
        "name": str(data.get("name", data["id"])),
        "description": str(data.get("description", "")).strip(),
        "tier": str(data.get("tier", "specialist")),
        "command": str(data.get("command", "")),
        "phases": len(phases),
        "gates": sorted(set(gate_types)),
        "quality_gate": bool(data.get("quality_gate_required", False)),
    }


def _dept_workflows() -> dict[str, list[dict]]:
    result: dict[str, list[dict]] = {}
    for dept_dir in (REPO_ROOT / "departments").iterdir():
        if not dept_dir.is_dir() or "vendor" in dept_dir.parts:
            continue
        wf_dir = dept_dir / "workflows"
        if not wf_dir.is_dir():
            continue
        entries = []
        for wf_yaml in sorted(wf_dir.glob("*.yaml")):
            entry = _workflow_entry(wf_yaml)
            if entry:
                entries.append(entry)
        if entries:
            result[dept_dir.name] = entries
    return result


def generate() -> str:
    """Return the full WORKFLOWS-CATALOG.md content."""
    dept_workflows = _dept_workflows()
    total = sum(len(v) for v in dept_workflows.values())
    tiers: dict[str, int] = {}
    for entries in dept_workflows.values():
        for entry in entries:
            tiers[entry["tier"]] = tiers.get(entry["tier"], 0) + 1

    lines = [
        "# ArkaOS Workflows Catalog",
        "",
        "> Generated by `scripts/workflows_catalog_gen.py`; do not edit. Regenerate",
        "> after touching any workflow YAML, department layout, or VERSION.",
        "",
        f"**{total} workflows** across {len(dept_workflows)} departments.",
        "",
        "## Summary",
        "",
        "| Department | Workflows |",
        "| --- | --- |",
    ]
    for slug in sorted(dept_workflows):
        title = DEPT_TITLES.get(slug, slug)
        lines.append(f"| {title} (`{slug}`) | {len(dept_workflows[slug])} |")
    lines.append(f"| **Total** | **{total}** |")
    lines.append("")
    lines.append("| Tier | Count |")
    lines.append("| --- | --- |")
    for tier in sorted(tiers):
        lines.append(f"| {TIER_LABELS.get(tier, tier)} | {tiers[tier]} |")
    lines.append("")

    for slug in sorted(dept_workflows):
        title = DEPT_TITLES.get(slug, slug)
        lines.append(f"## {title} (`{slug}`)")
        lines.append("")
        lines.append("| Workflow | Tier | Command | Phases | Gates | QG |")
        lines.append("| --- | --- | --- | --- | --- | --- |")
        for entry in dept_workflows[slug]:
            gates = ", ".join(entry["gates"]) if entry["gates"] else "—"
            qg = "yes" if entry["quality_gate"] else "—"
            lines.append(
                f"| `{entry['id']}` | {TIER_LABELS.get(entry['tier'], entry['tier'])} | "
                f"`{entry['command']}` | {entry['phases']} | {gates} | {qg} |"
            )
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    content = generate()
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"workflows catalog generated: {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
