#!/usr/bin/env python3
"""Run the ArkaOS benchmark harness and persist results.

Writes:
- benchmarks/results.json  -- machine-readable, consumed by the wiki
- benchmarks/results.md     -- human-readable summary table

Usage:
    python scripts/bench/run.py                 # default 50 runs
    python scripts/bench/run.py --runs 100
    python scripts/bench/run.py --runs 30 --no-write   # print only
"""
from __future__ import annotations

import argparse
import json
import platform
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from scripts.bench import harness  # noqa: E402

_OUT_DIR = _REPO_ROOT / "benchmarks"


def _environment() -> dict:
    """Capture the machine environment (numbers are machine-relative)."""
    return {
        "python": platform.python_version(),
        "platform": platform.platform(),
        "machine": platform.machine(),
    }


def _synapse_section(sl: dict) -> list[str]:
    """Render the Synapse latency section."""
    prof = sl["injection_profile"]
    return [
        "## Synapse context injection (engine-only, no vector store)",
        "",
        f"- Registered layers: **{sl['layer_count']}**",
        f"- Cold injection (cache cleared each run): "
        f"p50 **{sl['cold_ms']['p50']} ms**, mean {sl['cold_ms']['mean']} ms, "
        f"min {sl['cold_ms']['min']} ms, max {sl['cold_ms']['max']} ms "
        f"({sl['cold_ms']['runs']} runs)",
        f"- Warm injection (cached): "
        f"p50 **{sl['warm_ms']['p50']} ms**, mean {sl['warm_ms']['mean']} ms "
        f"({sl['warm_ms']['runs']} runs)",
        "- The small cold/warm delta is expected: cacheable layers are a "
        "minority of total compute, so warming the cache saves only a few ms.",
        f"- Representative injection: {prof['layers_computed']} layers computed, "
        f"{prof['layers_skipped']} skipped, {prof['tokens_injected']} tokens injected",
        "",
    ]


def _handoff_section(ho: dict) -> list[str]:
    """Render the subagent handoff section."""
    return [
        "## Subagent handoff artifact",
        "",
        f"- Measured (representative artifact): **{ho['measured_tokens']} word-tokens** "
        f"({ho['prompt_chars']} chars). 'word-tokens' is a whitespace-split estimate, "
        "not a BPE tokenizer count.",
        f"- Previously documented claim: {ho['documented_claim']}",
        "",
    ]


def _routing_section(ra: dict) -> list[str]:
    """Render the routing accuracy section + table."""
    out = [
        "## Routing accuracy (DepartmentLayer keyword detection)",
        "",
        f"- **{ra['correct']}/{ra['total']} = {ra['accuracy_pct']}%** on a fixed "
        "labelled prompt set",
        "",
        "| Prompt | Expected | Detected | OK |",
        "|---|---|---|:--:|",
    ]
    for d in ra["details"]:
        mark = "yes" if d["ok"] else "no"
        prompt = d["prompt"] if len(d["prompt"]) <= 48 else d["prompt"][:45] + "..."
        out.append(f"| {prompt} | {d['expected']} | {d['detected']} | {mark} |")
    out.append("")
    return out


def render_markdown(results: dict, env: dict) -> str:
    """Render a human-readable benchmark summary."""
    header = [
        "# ArkaOS Benchmarks",
        "",
        "> Generated by `python scripts/bench/run.py`. Timings are "
        "machine-relative; routing accuracy and handoff size are deterministic.",
        "",
        f"**Environment:** Python {env['python']} - {env['platform']}",
        "",
    ]
    return "\n".join(header
                     + _synapse_section(results["synapse_latency"])
                     + _handoff_section(results["subagent_handoff"])
                     + _routing_section(results["routing_accuracy"]))


def main() -> int:
    """Entry point."""
    parser = argparse.ArgumentParser(description="Run ArkaOS benchmarks")
    parser.add_argument("--runs", type=int, default=50, help="Latency samples (default 50)")
    parser.add_argument("--no-write", action="store_true", help="Print only, do not write files")
    args = parser.parse_args()

    env = _environment()
    results = harness.run_all(runs=args.runs)
    payload = {"environment": env, "results": results}
    md = render_markdown(results, env)

    if args.no_write:
        print(json.dumps(payload, indent=2))
        print("\n" + md)
        return 0

    _OUT_DIR.mkdir(exist_ok=True)
    (_OUT_DIR / "results.json").write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    (_OUT_DIR / "results.md").write_text(md + "\n", encoding="utf-8")
    print(f"Wrote {_OUT_DIR / 'results.json'} and {_OUT_DIR / 'results.md'}")
    print("\n" + md)
    return 0


if __name__ == "__main__":
    sys.exit(main())
