/**
 * ArkaOS menu bar launcher wiring (Foundation PR-5; Windows host #548).
 *
 * Deploys bin/arka-menubar.py to the purge-proof ~/.arkaos/bin/ (the
 * scheduler-daemon.py pattern — SNAPSHOT_DIRS does not ship bin/, and a
 * launchd unit anchored at an npx cache dies on `npm cache clean`; the
 * PR-1 QG blocker) and manages the login integration per platform:
 *
 *   darwin  the io.wizardingcode.arkaos.menubar LaunchAgent (launchd)
 *   win32   a Startup-folder .vbs that runs pythonw hidden at login —
 *           a Scheduled Task with an onlogon trigger needs elevation,
 *           the per-user Startup folder does not
 *
 * Every other platform reports { action: "unsupported" } gracefully.
 * Default-on (operator decision, PR-5 Phase 0 — same posture as the
 * PR-1 updater) with a persisted opt-out marker so `npx arkaos menubar
 * disable` survives future updates. ESM, Node + Bun, no interactive
 * prompts. Unit generation (`unitFor`) is pure so it is unit-tested
 * without touching the OS (autoupdate.js precedent).
 */

import { execFileSync } from "node:child_process";
import {
  chmodSync, copyFileSync, existsSync, mkdirSync, rmSync, writeFileSync,
} from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { getArkaosPython } from "./python-resolver.js";

export const MENUBAR_LABEL = "io.wizardingcode.arkaos.menubar";

function defaultRepoRoot() {
  return join(dirname(fileURLToPath(import.meta.url)), "..");
}

/** XML-escape a value interpolated into plist content — `&` and `<`
 *  are legal in macOS paths and would otherwise corrupt the plist into
 *  an opaque `launchctl load` failure (QG M1). */
export function xmlEscape(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&apos;");
}

/** Pure: the opt-out marker path — written by disable(), honored by
 *  ensureDefaultEnabled(). */
export function optoutPath(home = homedir()) {
  return join(home, ".arkaos", "menubar.optout");
}

/** Pure: where the menu bar script lives after deployment. */
export function menubarScriptPath(home = homedir()) {
  return join(home, ".arkaos", "bin", "arka-menubar.py");
}

/** Pure-ish: the per-user Startup folder. %APPDATA% wins for the real
 *  home (redirected-profile setups); the derived default keeps tests
 *  hermetic with a temp home. */
export function startupDir(home = homedir()) {
  if (home === homedir() && process.env.APPDATA) {
    return join(process.env.APPDATA, "Microsoft", "Windows", "Start Menu", "Programs", "Startup");
  }
  return join(home, "AppData", "Roaming", "Microsoft", "Windows", "Start Menu", "Programs", "Startup");
}

/** Pure: the Startup-folder launcher path (win32 twin of the plist). */
export function startupScriptPath(home = homedir()) {
  return join(startupDir(home), "ArkaOS Menubar.vbs");
}

/** Prefer the console-less pythonw.exe sibling — a python.exe login item
 *  flashes a console window at every logon. */
export function windowsInterpreterFor(pythonPath) {
  if (!pythonPath || !pythonPath.toLowerCase().endsWith("python.exe")) return pythonPath;
  const pythonw = pythonPath.slice(0, -"python.exe".length) + "pythonw.exe";
  return existsSync(pythonw) ? pythonw : pythonPath;
}

/**
 * Pure: the LaunchAgent plist for the menu bar app. macOS-only — throws
 * on any other platform (callers catch and report "unsupported").
 * KeepAlive is intentionally false: "Quit" must stick until next login;
 * RunAtLoad brings it back at login. LimitLoadToSessionType=Aqua +
 * ProcessType=Interactive mark it as a GUI agent (idiomatic launchd).
 */
export function unitFor(os, { home, pythonPath, scriptPath }) {
  if (os === "win32") {
    // A .vbs (not .cmd) because WScript.Shell.Run with window style 0 is
    // the only Startup-folder mechanism that never flashes a console.
    // VBS escapes a quote by doubling it — but '"' is illegal in Windows
    // paths, so the doubled quotes below are structure, not escaping.
    const content = [
      "' ArkaOS menu bar launcher — generated by installer/menubar.js",
      "' Runs the tray app hidden at login. Remove via: npx arkaos menubar disable",
      'Set shell = CreateObject("WScript.Shell")',
      `shell.Run """${pythonPath}"" ""${scriptPath}""", 0, False`,
      "",
    ].join("\r\n");
    return {
      kind: "startup",
      files: [{ path: startupScriptPath(home), content }],
    };
  }
  if (os !== "darwin") {
    throw new Error(`menu bar launcher is macOS/Windows-only (got ${os})`);
  }
  const log = join(home, ".arkaos", "logs", "menubar.log");
  // PATH: launchd defaults carry no node; ~/.arkaos/bin carries the arka
  // wrappers. nvm/fnm installs still resolve through the app's own
  // shutil.which guard, which logs instead of failing silently (QG M5).
  const pathValue = `/opt/homebrew/bin:/usr/local/bin:${join(home, ".arkaos", "bin")}:/usr/bin:/bin:/usr/sbin:/sbin`;
  const content = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${MENUBAR_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${xmlEscape(pythonPath)}</string>
    <string>${xmlEscape(scriptPath)}</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>${xmlEscape(pathValue)}</string>
  </dict>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <false/>
  <key>LimitLoadToSessionType</key>
  <string>Aqua</string>
  <key>ProcessType</key>
  <string>Interactive</string>
  <key>StandardOutPath</key>
  <string>${xmlEscape(log)}</string>
  <key>StandardErrorPath</key>
  <string>${xmlEscape(log)}</string>
</dict>
</plist>
`;
  return {
    kind: "launchd",
    files: [
      {
        path: join(home, "Library", "LaunchAgents", `${MENUBAR_LABEL}.plist`),
        content,
      },
    ],
  };
}

/**
 * Copy bin/arka-menubar.py into ~/.arkaos/bin/ (mirrors the
 * scheduler-daemon.py deployment). Returns true when deployed.
 */
export function deployMenubarScript({ repoRoot = defaultRepoRoot(), home = homedir() } = {}) {
  const src = join(repoRoot, "bin", "arka-menubar.py");
  if (!existsSync(src)) return false;
  const dest = menubarScriptPath(home);
  mkdirSync(dirname(dest), { recursive: true });
  copyFileSync(src, dest);
  try { chmodSync(dest, 0o755); } catch { /* NTFS/ACL no-op */ }
  return true;
}

// Shell-free exec (QG M1): argv array via execFileSync — a home path
// containing quotes/backticks/$() can never escape into a shell.
function _silent(file, args) {
  try {
    execFileSync(file, args, { stdio: "pipe" });
    return true;
  } catch {
    return false;
  }
}

// The tray process query, shared by disable() (stop) and menubarHealthy()
// (live probe) — the win32 twin of `launchctl list <label>`. Matching on
// the command line finds the app whichever interpreter launched it.
const WIN32_TRAY_QUERY =
  "Get-CimInstance Win32_Process -Filter \"Name='pythonw.exe' or Name='python.exe'\"" +
  " | Where-Object { $_.CommandLine -match 'arka-menubar' }";

function resolvedPython() {
  if (process.platform === "win32") {
    return windowsInterpreterFor(getArkaosPython() || "pythonw.exe");
  }
  return getArkaosPython() || "/usr/bin/python3";
}

export function enable({ repoRoot = defaultRepoRoot(), home = homedir() } = {}) {
  if (process.platform !== "darwin" && process.platform !== "win32") {
    return { ok: false, path: "", message: "Menu bar launcher is macOS/Windows-only." };
  }
  if (!deployMenubarScript({ repoRoot, home })) {
    return { ok: false, path: "", message: "bin/arka-menubar.py not found in the package." };
  }
  const unit = unitFor(process.platform, {
    home,
    pythonPath: resolvedPython(),
    scriptPath: menubarScriptPath(home),
  });
  mkdirSync(join(home, ".arkaos", "logs"), { recursive: true });
  for (const f of unit.files) {
    mkdirSync(dirname(f.path), { recursive: true });
    writeFileSync(f.path, f.content, "utf8");
  }
  if (existsSync(optoutPath(home))) rmSync(optoutPath(home));
  const mainPath = unit.files[0].path;
  if (process.platform === "win32") {
    // Start now — wscript returns immediately (shell.Run does not wait),
    // so this is the launchctl-load parity, not a blocking call.
    if (!_silent("wscript.exe", [mainPath])) {
      return { ok: false, path: mainPath,
        message: "Startup entry written but the tray app could not start now — it will still start at next login." };
    }
    return { ok: true, path: mainPath,
      message: "Menu bar launcher enabled (look for ▲ in the system tray)." };
  }
  _silent("launchctl", ["unload", mainPath]);
  if (!_silent("launchctl", ["load", "-w", mainPath])) {
    return { ok: false, path: mainPath,
      message: "Plist written but launchctl load failed — it will still start at next login." };
  }
  return { ok: true, path: mainPath,
    message: "Menu bar launcher enabled (look for ▲ in the macOS menu bar)." };
}

export function disable({ home = homedir() } = {}) {
  if (process.platform !== "darwin" && process.platform !== "win32") {
    return { ok: false, path: "", message: "Menu bar launcher is macOS/Windows-only." };
  }
  if (process.platform === "win32") {
    const vbs = startupScriptPath(home);
    // Best-effort stop of the running tray (launchctl-unload parity).
    _silent("powershell.exe", ["-NoProfile", "-Command",
      `${WIN32_TRAY_QUERY} | ForEach-Object { Stop-Process -Id $_.ProcessId -Force }`]);
    if (existsSync(vbs)) rmSync(vbs);
    mkdirSync(join(home, ".arkaos"), { recursive: true });
    writeFileSync(optoutPath(home), new Date().toISOString(), "utf8");
    return { ok: true, path: vbs, message: "Menu bar launcher disabled (opt-out persisted)." };
  }
  const plist = join(home, "Library", "LaunchAgents", `${MENUBAR_LABEL}.plist`);
  _silent("launchctl", ["unload", plist]);
  if (existsSync(plist)) rmSync(plist);
  // Persisted opt-out: future `npx arkaos update` runs must not re-enable.
  mkdirSync(join(home, ".arkaos"), { recursive: true });
  writeFileSync(optoutPath(home), new Date().toISOString(), "utf8");
  return { ok: true, path: plist, message: "Menu bar launcher disabled (opt-out persisted)." };
}

export function status({ home = homedir(), platform = process.platform } = {}) {
  if (platform === "win32") {
    const vbs = startupScriptPath(home);
    return {
      installed: existsSync(vbs) && existsSync(menubarScriptPath(home)),
      supported: true,
      optout: existsSync(optoutPath(home)),
      kind: "startup",
      path: vbs,
    };
  }
  if (platform !== "darwin") {
    return { installed: false, supported: false, optout: false,
      message: "menu bar launcher is macOS/Windows-only" };
  }
  const plist = join(home, "Library", "LaunchAgents", `${MENUBAR_LABEL}.plist`);
  return {
    installed: existsSync(plist) && existsSync(menubarScriptPath(home)),
    supported: true,
    optout: existsSync(optoutPath(home)),
    kind: "launchd",
    path: plist,
  };
}

/**
 * Doctor probe (QG M2): file presence alone cannot detect the primary
 * failure mode (agent files present, process dead at import). Composes
 * status() with a live `launchctl list <label>` query (exit 0 iff the
 * job is loaded in this session). `exec` and `platform` are injectable
 * so every branch is testable without touching launchd.
 */
export function menubarHealthy({
  home = homedir(),
  platform = process.platform,
  exec = (file, args) => _silent(file, args),
} = {}) {
  if (platform === "win32") {
    const s = status({ home, platform });
    // A persisted opt-out is a healthy, chosen state — not a warning.
    if (s.optout) return true;
    if (!s.installed) return false;
    // Live probe: exit 0 iff a tray process is actually running — the
    // `launchctl list` twin (files present, process dead is the primary
    // failure mode on Windows too).
    return exec("powershell.exe", ["-NoProfile", "-Command",
      `if (${WIN32_TRAY_QUERY}) { exit 0 } else { exit 1 }`]);
  }
  if (platform !== "darwin") return true; // not applicable
  // platform flows down — status() reading the REAL process.platform
  // here broke the injectable branches on the Linux CI runner (the
  // opt-out branch returned false off-macOS).
  const s = status({ home, platform });
  // A persisted opt-out is a healthy, chosen state — not a warning.
  if (s.optout) return true;
  if (!s.installed) return false;
  return exec("launchctl", ["list", MENUBAR_LABEL]);
}

/** Default-on wiring for install/update flows: enable unless the user
 *  opted out or the platform is unsupported. Never throws. */
export function ensureDefaultEnabled({ repoRoot = defaultRepoRoot(), home = homedir() } = {}) {
  const s = status({ home });
  if (!s.supported) return { action: "unsupported" };
  if (s.optout) return { action: "optout" };
  if (s.installed) {
    // Refresh script + plist content in place (paths may change between
    // versions). Deliberately no unload/load here: the refreshed unit
    // only takes effect at next login — a reload storm on every update
    // would flicker the running app (QG minor, documented honestly).
    try {
      deployMenubarScript({ repoRoot, home });
      const unit = unitFor(process.platform, {
        home, pythonPath: resolvedPython(), scriptPath: menubarScriptPath(home),
      });
      for (const f of unit.files) writeFileSync(f.path, f.content, "utf8");
    } catch { /* refresh is best-effort */ }
    return { action: "already-enabled" };
  }
  const r = enable({ repoRoot, home });
  return { action: r.ok ? "enabled" : "partial", message: r.message };
}

export async function menubar(args = []) {
  const action = (args[0] || "status").toLowerCase();
  if (action === "enable") {
    const r = enable();
    console.log(`  ${r.ok ? "✓" : "⚠"} ${r.message}${r.path ? `\n    ${r.path}` : ""}`);
  } else if (action === "disable") {
    const r = disable();
    console.log(`  ${r.ok ? "✓" : "⚠"} ${r.message}`);
  } else if (action === "status") {
    const s = status();
    if (!s.supported) console.log(`  Menu bar launcher not supported here: ${s.message}`);
    else if (s.optout) console.log(`  Menu bar: DISABLED by user opt-out\n    (re-enable: npx arkaos menubar enable)`);
    else console.log(`  Menu bar: ${s.installed ? "ENABLED" : "disabled"} (${s.kind})\n    ${s.path}`);
  } else {
    console.error(`  Unknown menubar action: ${action}. Use enable | disable | status.`);
    process.exitCode = 1;
  }
}
